USE testdb

INSERT INTO TB_USER (ID, NAME, AGE, JOB)
VALUES('U001', 'USER', '20', 'STUDENT')

INSERT INTO TB_USER (ID, NAME, AGE, JOB)
VALUES('U002', 'USER', '29', 'DESIGNER')

INSERT INTO TB_USER (ID, NAME, AGE, JOB)
VALUES('U003', 'USER', '30', 'PROGRAMMER')

INSERT INTO TB_USER (ID, NAME, AGE, JOB)
VALUES('U004', 'USER', '25', 'DANCER')

INSERT INTO TB_USER (ID, NAME, AGE, JOB)
VALUES('U005', 'USER', '32', 'ENGINEER')


